# Generated by Django 5.2.7 on 2025-10-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productcalculation',
            name='id',
        ),
        migrations.AddField(
            model_name='productcalculation',
            name='pk',
            field=models.CompositePrimaryKey('product_id', 'calculation_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
