# Generated by Django 5.2.7 on 2025-10-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_calculation_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_field',
            field=models.IntegerField(verbose_name='product_field_label'),
        ),
    ]
