# Generated by Django 5.2.6 on 2025-09-28 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('license_plate', models.CharField(default='Unknown', max_length=100, verbose_name='Госномер')),
                ('VIN', models.CharField(max_length=100, verbose_name='VIN')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'db_table': 'cars',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='DepreciationCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Черновик'), (2, 'Сформирован'), (3, 'Завершён'), (4, 'Отклонён'), (5, 'Удалён')], default=1, verbose_name='Статус')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('formation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('sum', models.IntegerField(blank=True, null=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расчёт',
                'verbose_name_plural': 'Расчёты',
                'db_table': 'depreciation_calculations',
                'ordering': ('-formation_date',),
            },
        ),
        migrations.CreateModel(
            name='CarDepreciationCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробег (км)')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.car')),
                ('depreciation_calculation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.depreciationcalculation')),
            ],
            options={
                'verbose_name': 'М-М',
                'verbose_name_plural': 'М-М',
                'db_table': 'car_depreciation_calculation',
                'ordering': ('pk',),
            },
        ),
    ]
