# Generated by Django 5.2.7 on 2025-10-20 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('license_plate', models.CharField(max_length=100, verbose_name='Госномер')),
                ('vin', models.CharField(max_length=100, verbose_name='VIN')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'db_table': 'cars',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершен'), (4, 'Отклонен'), (5, 'Удален')], default=1, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_formation', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('summ', models.IntegerField(blank=True, null=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Амортизация',
                'verbose_name_plural': 'Амортизации',
                'db_table': 'depreciations',
                'ordering': ('-date_formation',),
            },
        ),
        migrations.CreateModel(
            name='CarDepreciation',
            fields=[
                ('pk', models.CompositePrimaryKey('car_id', 'depreciation_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('mileage', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.car')),
                ('depreciation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.depreciation')),
            ],
            options={
                'verbose_name': 'Амортизация автомобиля',
                'verbose_name_plural': 'Амортизации автомобилей',
                'db_table': 'car_depreciation',
                'ordering': ('pk',),
            },
        ),
    ]
