# Generated by Django 5.2.6 on 2025-09-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='VIN',
            field=models.CharField(max_length=100, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='car',
            name='licence_plate',
            field=models.CharField(max_length=100, verbose_name='Госномер'),
        ),
    ]
