# Generated by Django 5.2.6 on 2025-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_depreciationcalculation_cardepreciationcalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciationcalculation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Черновик'), (2, 'Сформирован'), (3, 'Завершён'), (4, 'Отклонён'), (5, 'Удалён')], default=1, verbose_name='Статус'),
        ),
    ]
