# Generated by Django 5.2.6 on 2025-09-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_depreciationcalculation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='licence_plate',
        ),
    ]
