# Generated by Django 5.2.6 on 2025-09-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_car_licence_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Госномер'),
        ),
    ]
